spring:
  datasource:
    url: jdbc:mysql://localhost:52000/employee
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: employeeservice
server:
  port: 8082
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
message: "it is dev environment"
